version: '3'
services:
  nodejs-backend:
    build: .
    ports:
      - "3000:3000"
  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - "./database/database.env"
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: